# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 08:43
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('treeView', '0002_treeview_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeview',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='treeView.treeView', verbose_name='lower-case'),
        ),
    ]
