# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userrank',
            field=models.IntegerField(null=True),
        ),
    ]
