# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_auto_20170717_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userrank',
            field=models.IntegerField(null=0),
        ),
    ]
