# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 13:40
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPush', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
