# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 17:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPush', '0004_newspost_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='headline',
            field=models.CharField(default=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'), max_length=50),
        ),
    ]
