# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPush', '0005_auto_20170716_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='headline',
            field=models.CharField(max_length=50),
        ),
    ]
