# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPush', '0006_auto_20170716_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='headline',
        ),
    ]
