# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 11:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPush', '0008_newspost_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.CharField(max_length=50, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='cover',
            field=models.ImageField(upload_to='Img', verbose_name='\u5c01\u9762\u56fe'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='headline',
            field=models.CharField(default='', max_length=50, verbose_name='\u6458\u8981'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='timestamp',
            field=models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u6807\u9898'),
        ),
    ]
